### ISSUE TITLE
Token templates don't appear for other players and feel generally buggy

### ISSUE THREAD

**Issue by tom95** [cmfcmf/roc-and-roll#36]

**Comment by cmfcmf** [comment]
Figured out why: When adding a new character from a token template, we currently always set its visibility to gmOnly: https://github.com/cmfcmf/roc-and-roll/blob/126701580cd2709f01128d9ded13bb4a0c4d79d7/src/client/components/map/MapContainer.tsx#L173

I wonder if that is the expected behavior.

As a first step, I added a big warning in ac21ff34341505b46a62a45afcdc64f07f4d78b7 that is shown when a token is only visible to the GM:

![image](https://user-images.githubusercontent.com/2145092/117955505-65985080-b318-11eb-839f-6b93c5d05d9a.png)

It also looks like we do not yet have a dropdown to change the visibility of a character or character template.

**Comment by tom95** [comment]
I added a toggle for visibility in 386f440

**Comment by tom95** [comment]
And they are now also visible by default since dc793a5
