### ISSUE TITLE
We need fog of war

### ISSUE THREAD

**Issue by cmfcmf** [cmfcmf/roc-and-roll#48]

**Comment by tom95** [comment]
First basic impl is now in via 546409895be2a0b8c19f1ffc1355bafcc77c7c86. Things that are still to do:
- [ ] allow changing brush to hide instead of show
- [ ] figure out an elegant manner to support our infinitely scrolling canvas. The grid is doing so by always generating correctly-sized rectangles based on the viewport, which we could do as well, for all areas outside of the ones where revealed areas are. There is a bounding box method on shape we could use for that purpose.
- [ ] the brush is rectangular and leaves not-so-pretty jagged lines. We could either experiment with a different type of brush shape (e.g. circle with 20 vertices?) or, maybe, we could try and smooth out the rectangles by averaging positions of vertices with their neighbors? not sure how that would feel

**Comment by tom95** [comment]
I will create a separate issue for the brush and close this one. The other two points have been addressed.

**Comment by cmfcmf** [comment]
Great work 👍
