### ISSUE TITLE
Typing on template names is buggy

### ISSUE THREAD

**Issue by corinnaj** [cmfcmf/roc-and-roll#55]
find out how to properly use `useOptimisticServerDebounce()`

**Comment by cmfcmf** [comment]
This should now be fixed. `useOptimisticDebouncedServerUpdate` has always been slightly buggy, because it didn't interact well with the way React Concurrent Mode works. 
I changed its signature in https://github.com/cmfcmf/roc-and-roll/commit/1b59e07d93cb8f1beb4871360328ad47bca5da27 so that it now always takes a selector function on the server state, instead of taking a plain value. This removes the general bugginess.

DiceTemplates were extra buggy, I think, because they used a custom [`applyChange`](https://github.com/cmfcmf/roc-and-roll/commit/1b59e07d93cb8f1beb4871360328ad47bca5da27#diff-67e03b48f4122c348799efcba230ea8c4b3cab9f269a5e477ce65ba8441b1b8fL684-L697) function instead of returning actions from the callback passed to `useOptimisticDebouncedServerUpdate`.
 To fix that, I had to add an id to each `DiceTemplatePart` and introduce new Redux actions for updating and removing a `DiceTemplatePart`, which then allowed me to use `useOptimisticDebouncedServerUpdate` as intended.
